<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.6.7 on win32)" generated="20200423 12:27:22.340" rpa="false">
<suite id="s1" name="Test amazon" source="C:\Users\VickyWin10\Robot Projects\Test_Robot_Web\Tests\Test_amazon.robot">
<test id="s1-t1" name="Test Launch_amazon">
<kw name="Provided precondition">
<kw name="Open Browser" library="Selenium2Library">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<arguments>
<arg>https://www.amazon.in/</arg>
<arg>ie</arg>
</arguments>
<msg timestamp="20200423 12:27:22.668" level="INFO">Opening browser 'ie' to base url 'https://www.amazon.in/'.</msg>
<kw name="Capture Page Screenshot" library="Selenium2Library">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20200423 12:32:32.999" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /session/eb79438a-956d-47a7-924b-06f560eefc5a/screenshot</msg>
<msg timestamp="20200423 12:32:35.012" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002377E889C50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eb79438a-956d-47a7-924b-06f560eefc5a/screenshot</msg>
<msg timestamp="20200423 12:32:37.029" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002377E889BE0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eb79438a-956d-47a7-924b-06f560eefc5a/screenshot</msg>
<msg timestamp="20200423 12:32:39.127" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=59541): Max retries exceeded with url: /session/eb79438a-956d-47a7-924b-06f560eefc5a/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002377E889CC0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))</msg>
<status status="FAIL" starttime="20200423 12:32:25.997" endtime="20200423 12:32:39.127"></status>
</kw>
<msg timestamp="20200423 12:32:39.127" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=59541): Max retries exceeded with url: /session/eb79438a-956d-47a7-924b-06f560eefc5a/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002377E889CC0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))</msg>
<msg timestamp="20200423 12:32:39.143" level="FAIL">TimeoutException: Message: Timed out waiting for page to load.
</msg>
<status status="FAIL" starttime="20200423 12:27:22.668" endtime="20200423 12:32:39.143"></status>
</kw>
<status status="FAIL" starttime="20200423 12:27:22.668" endtime="20200423 12:32:39.143"></status>
</kw>
<tags>
<tag>DEBUG</tag>
</tags>
<status status="FAIL" starttime="20200423 12:27:22.668" endtime="20200423 12:32:39.143" critical="yes">TimeoutException: Message: Timed out waiting for page to load.
</status>
</test>
<doc>Suite description</doc>
<status status="FAIL" starttime="20200423 12:27:22.356" endtime="20200423 12:32:39.158"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">DEBUG</stat>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Test amazon">Test amazon</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200423 12:32:32.999" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /session/eb79438a-956d-47a7-924b-06f560eefc5a/screenshot</msg>
<msg timestamp="20200423 12:32:35.012" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002377E889C50&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eb79438a-956d-47a7-924b-06f560eefc5a/screenshot</msg>
<msg timestamp="20200423 12:32:37.029" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002377E889BE0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eb79438a-956d-47a7-924b-06f560eefc5a/screenshot</msg>
<msg timestamp="20200423 12:32:39.127" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=59541): Max retries exceeded with url: /session/eb79438a-956d-47a7-924b-06f560eefc5a/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002377E889CC0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))</msg>
</errors>
</robot>
